default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost


development:
  <<: *default
  database: beta_development

test:
  <<: *default
  database: beta_test

production:
  <<: *default
  database: beta_production
  username: sample_app
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>